/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package trabalho.libraryproject.view;


import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import trabalho.libraryproject.connection.SQLiteConnector;
import trabalho.libraryproject.controller.BookController;
import trabalho.libraryproject.controller.UserController;
import trabalho.libraryproject.model.DAO.BookDAODataBase;
import trabalho.libraryproject.model.DAO.BookDAOFile;
import trabalho.libraryproject.model.DAO.IDao;
import trabalho.libraryproject.model.DAO.UserDAODataBase;
import trabalho.libraryproject.model.DAO.UserDAOFile;
import trabalho.libraryproject.model.entities.Book;
import trabalho.libraryproject.model.entities.User;
import trabalho.libraryproject.view.TableModel.TMCadBook;

/**
 *
 * @author  igorxf
 */
public class JDialogSelectBook extends javax.swing.JDialog {
    
   
    private BookController bookController;
    private UserController userController;
    private User user;
    private Book bookEscolhido;
   

    
    
    public JDialogSelectBook(java.awt.Frame parent, boolean modal,  User u) throws SQLException {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        
        IDao userJ = new UserDAOFile("ListagemDisciplinas.json");
        
        SQLiteConnector conexao = new SQLiteConnector("banco.sqlite");
        IDao userDao = new UserDAODataBase(conexao.getConnection());
        this.userController = new UserController(userDao);
        
        
        IDao bookJ =new BookDAOFile("ListagemAlunos.json");
        
        SQLiteConnector conexao2 = new SQLiteConnector("banco.sqlite");
        IDao bookDao = new BookDAODataBase(conexao2.getConnection());
        this.bookController = new BookController(bookDao);
        initData();
        this.user = u ;
    }
    
    public JDialogSelectBook(java.awt.Dialog parent, boolean modal,  User u ) throws SQLException {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        
         //IDao userJ = new UserDAOFile("ListagemDisciplinas.json");
        
        SQLiteConnector conexao = new SQLiteConnector("banco.sqlite");
        IDao userDao = new UserDAODataBase(conexao.getConnection());
        this.userController = new UserController(userDao);
        
        
        //IDao bookJ =new BookDAOFile("ListagemAlunos.json");
        
        SQLiteConnector conexao2 = new SQLiteConnector("banco.sqlite");
        IDao bookDao = new BookDAODataBase(conexao2.getConnection());
        this.bookController = new BookController(bookDao);
        initData();
        this.user = u;
        
        
    }
    
    private void initData(){

        this.editando = true;

        this.habilitarCampos(false);
        this.limparCampos();

        this.atualizarTabela();
    }
    
    public void habilitarCampos(boolean flag) {
        edtTitle.setEnabled(flag);
       edtISBN.setEnabled(flag);
       edtAuthor.setEnabled(flag);
       edtPublicationYear.setEnabled(flag);
    }

    public void limparCampos() {
       edtTitle.setText("");
       edtISBN.setText("");
       edtAuthor.setText("");
       edtPublicationYear.setText("");
    }

    public void objetoParaCampos(Book b) {
       edtTitle.setText(b.getTitle());
       edtISBN.setText(b.getIsbn());
       edtAuthor.setText(b.getAuthor().getCpf());
       edtPublicationYear.setText(b.getPublicationYear() + "");
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblSelectBook = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        grdBook = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnSelecBook = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        edtTitle = new javax.swing.JTextField();
        lblAuthor = new javax.swing.JLabel();
        edtAuthor = new javax.swing.JTextField();
        lblISBN = new javax.swing.JLabel();
        edtISBN = new javax.swing.JTextField();
        lblPublicationYear = new javax.swing.JLabel();
        edtPublicationYear = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        lblSelectBook.setBackground(new java.awt.Color(102, 204, 255));
        lblSelectBook.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblSelectBook.setForeground(new java.awt.Color(255, 255, 255));
        lblSelectBook.setText("Select Book ");
        jPanel1.add(lblSelectBook);

        grdBook.setBackground(new java.awt.Color(255, 255, 255));
        grdBook.setForeground(new java.awt.Color(0, 0, 0));
        grdBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        grdBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grdBookMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(grdBook);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        btnSelecBook.setBackground(new java.awt.Color(0, 204, 255));
        btnSelecBook.setForeground(new java.awt.Color(255, 255, 255));
        btnSelecBook.setText("Select");
        btnSelecBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecBookActionPerformed(evt);
            }
        });
        jPanel2.add(btnSelecBook);

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));

        lblTitle.setBackground(new java.awt.Color(0, 0, 0));
        lblTitle.setForeground(new java.awt.Color(0, 0, 0));
        lblTitle.setText("Title :");

        edtTitle.setBackground(new java.awt.Color(255, 255, 255));
        edtTitle.setForeground(new java.awt.Color(0, 0, 0));

        lblAuthor.setForeground(new java.awt.Color(0, 0, 0));
        lblAuthor.setText("Author :");

        edtAuthor.setBackground(new java.awt.Color(255, 255, 255));
        edtAuthor.setForeground(new java.awt.Color(0, 0, 0));

        lblISBN.setForeground(new java.awt.Color(0, 0, 0));
        lblISBN.setText("ISBN :");

        edtISBN.setBackground(new java.awt.Color(255, 255, 255));
        edtISBN.setForeground(new java.awt.Color(0, 0, 0));

        lblPublicationYear.setBackground(new java.awt.Color(255, 255, 255));
        lblPublicationYear.setForeground(new java.awt.Color(0, 0, 0));
        lblPublicationYear.setText("Publication Year :");

        edtPublicationYear.setBackground(new java.awt.Color(255, 255, 255));
        edtPublicationYear.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblISBN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtISBN))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(77, 77, 77)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAuthor)
                    .addComponent(lblPublicationYear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(edtAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(edtPublicationYear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(edtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAuthor)
                    .addComponent(edtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblISBN)
                    .addComponent(edtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPublicationYear)
                    .addComponent(edtPublicationYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void grdBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grdBookMouseClicked
         Book b = this.getObjetoSelecionadoNaGrid();
         this.objetoParaCampos(b);
       
    }//GEN-LAST:event_grdBookMouseClicked

    private void btnSelecBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecBookActionPerformed
       this.bookEscolhido = this.getObjetoSelecionadoNaGrid();
       
        String ISBNEscolhido = bookEscolhido.getIsbn();
        
        Book bookExistente = bookController.update(ISBNEscolhido, edtTitle.getText(), edtISBN.getText(), edtAuthor.getText().formatted(args), edtPublicationYear.getText());

        if (alunoExistente == null) {
            JOptionPane.showMessageDialog(this, "Não existe aluno com esse cpf.");
        } else {
            this.habilitarCampos(true);
            this.objetoParaCampos(alunoExistente);
            this.editando = true;
            this.cpfEscolhido = alunoExistente.getCpf();
        }

    }//GEN-LAST:event_btnSelecBookActionPerformed

    public Book getObjetoSelecionadoNaGrid() {
        int linhaSelecionada = grdBook.getSelectedRow();

        if (linhaSelecionada >= 0) {
            TMCadBook tmCadBook = (TMCadBook) grdBook.getModel();

             Book book = tmCadBook.getObjetoBook(linhaSelecionada);
            return book;
        }
        
        return null;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelecBook;
    private javax.swing.JTextField edtAuthor;
    private javax.swing.JTextField edtISBN;
    private javax.swing.JTextField edtPublicationYear;
    private javax.swing.JTextField edtTitle;
    private javax.swing.JTable grdBook;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAuthor;
    private javax.swing.JLabel lblISBN;
    private javax.swing.JLabel lblPublicationYear;
    private javax.swing.JLabel lblSelectBook;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
