package trabalho.libraryproject.view;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */


import com.mycompany.projescolamvc.view.tablemodels.TMCadAluno;
import com.mycompany.projescolamvc.connection.SQLiteConnector;
import com.mycompany.projescolamvc.controller.AlunoController;
import com.mycompany.projescolamvc.controller.DisciplinaController;
import com.mycompany.projescolamvc.model.dao.AlunoDAOBanco;
import com.mycompany.projescolamvc.model.dao.AlunoDAOFile;
import com.mycompany.projescolamvc.model.dao.DisciplinaDAOBanco;
import com.mycompany.projescolamvc.model.dao.DisciplinaDAOFile;
import com.mycompany.projescolamvc.model.dao.IDao;
import com.mycompany.projescolamvc.model.entities.Aluno;
import com.mycompany.projescolamvc.model.entities.Disciplina;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import trabalho.libraryproject.connection.SQLiteConnector;
import trabalho.libraryproject.controller.AuthorController;
import trabalho.libraryproject.controller.BookController;
import trabalho.libraryproject.model.DAO.AuthorDAOFile;
import trabalho.libraryproject.model.DAO.BookDAOFile;
import trabalho.libraryproject.model.DAO.IDao;
import trabalho.libraryproject.model.entities.Author;
import trabalho.libraryproject.model.entities.Book;

/**
 *
 * @author  igorxf
 */
public class JDialogSelectAuthor extends javax.swing.JDialog {
    
    private boolean editando;
    private String cpfEscolhido;
    private AuthorController authorController;
    private BookController bookController;
    private Book book;
    private Author authorEscolhido;
   

    
    
    public JDialogSelectAuthor(java.awt.Frame parent, boolean modal,  Book b) throws SQLException {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        
        //IDao disciplinaDao = new DisciplinaDAOFile("ListagemDisciplinas.json");
        
        SQLiteConnector conexao = new SQLiteConnector("banco.sqlite");
        IDao bookDao = new BookDAOBanco(conexao.getConnection());
        this.bookController = new BookController(bookDao);
        
        
        //IDao alunoDao =new AlunoDAOFile("ListagemAlunos.json");
        
        SQLiteConnector conexao2 = new SQLiteConnector("banco.sqlite");
       // IDao authorDao = new AuthorDAOBanco(conexao2.getConnection());
        //this.authorController = new AuthorController(authorDao);
        initData();
        this.book = b;
    }
    
    public JDialogSelectAuthor(java.awt.Dialog parent, boolean modal,  Book b) throws SQLException {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        
        //IDao bookDao = new BookDAOFile("ListagemLivros.json");
        SQLiteConnector conexao = new SQLiteConnector("dataBase.sqlite");
        IDao bookDao = new BookDAOBanco(conexao.getConnection());
        this.bookController = new BookController(bookDao);
        
        //IDao authorDao =new AuthorDAOFile("ListagemAutores.json");
        SQLiteConnector conexao2 = new SQLiteConnector("banco.sqlite");
        IDao authorDao = new AuthorDAOBanco(conexao2.getConnection());
        this.authorController = new AuthorController(authorDao);
        initData();
        this.book = b;
    }
    
    private void initData(){

        this.editando = true;

        this.habilitarCampos(false);
        this.limparCampos();

        this.atualizarTabela();
    }
    
    public void habilitarCampos(boolean flag) {
        edtTitle.setEnabled(flag);
        edtMatricula.setEnabled(flag);
        edtNome.setEnabled(flag);
        edtIdade.setEnabled(flag);
        edtAnoIngresso.setEnabled(flag);
    }

    public void limparCampos() {
        edtCPF.setText("");
        edtMatricula.setText("");
        edtNome.setText("");
        edtIdade.setText("");
        edtAnoIngresso.setText("");
    }

    public void objetoParaCampos(Aluno p) {
       edtCPF.setText(p.getCpf());
       edtMatricula.setText(p.getMatricula());
       edtNome.setText(p.getNome());
       edtIdade.setText(p.getIdade() + "");
       edtAnoIngresso.setText(p.getAnoIngresso()+ "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAluno = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        grdAluno = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        lblAluno.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblAluno.setForeground(new java.awt.Color(0, 0, 0));
        lblAluno.setText("Select Author");
        jPanel1.add(lblAluno);

        grdAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(grdAluno);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private void grdAlunoMouseClicked(java.awt.event.MouseEvent evt) {                                       
       Aluno a = this.getObjetoSelecionadoNaGrid();
       this.objetoParaCampos(a);
    }
    
    public Aluno getObjetoSelecionadoNaGrid() {
        int linhaSelecionada = grdAluno.getSelectedRow();

        if (linhaSelecionada >= 0) {
            TMCadAluno tmCadAluno = (TMCadAluno) grdAluno.getModel();

             Aluno aluno = tmCadAluno.getObjetoAluno(linhaSelecionada);
            return aluno;
        }
        
        return null;
    }
    
    public void atualizarTabela() {
        List<Aluno> lista = this.alunoController.listarAlunos();
        TMCadAluno tmcadaluno = new TMCadAluno(lista);
        grdAluno.setModel(tmcadaluno);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable grdAluno;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAluno;
    // End of variables declaration//GEN-END:variables
}
