/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package trabalho.libraryproject.view;


import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import trabalho.libraryproject.controller.BookController;
import trabalho.libraryproject.controller.UserController;
import trabalho.libraryproject.model.entities.Book;
import trabalho.libraryproject.model.entities.User;
import trabalho.libraryproject.view.TableModel.TMCadBook;

/**
 *
 * @author  igorxf
 */
public class JDialogSelectBook extends javax.swing.JDialog {
    
   
    private BookController bookController;
    private UserController userController;
    private User user;
    private Book bookEscolhido;
   

    
    
    public JDialogSelectBook(java.awt.Frame parent, boolean modal,  Disciplina d) throws SQLException {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        
        //IDao disciplinaDao = new DisciplinaDAOFile("ListagemDisciplinas.json");
        
        SQLiteConnector conexao = new SQLiteConnector("banco.sqlite");
        IDao disciplinaDao = new DisciplinaDAOBanco(conexao.getConnection());
        this.disciplinaController = new DisciplinaController(disciplinaDao);
        
        
        //IDao alunoDao =new AlunoDAOFile("ListagemAlunos.json");
        
        SQLiteConnector conexao2 = new SQLiteConnector("banco.sqlite");
        IDao alunoDao = new AlunoDAOBanco(conexao2.getConnection());
        this.alunoController = new AlunoController(alunoDao);
        initData();
        this.dis = d;
    }
    
    public JDialogSelectBook(java.awt.Dialog parent, boolean modal,  Disciplina d) throws SQLException {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        
        //IDao disciplinaDao = new DisciplinaDAOFile("ListagemDisciplinas.json");
        SQLiteConnector conexao = new SQLiteConnector("banco.sqlite");
        IDao disciplinaDao = new DisciplinaDAOBanco(conexao.getConnection());
        this.disciplinaController = new DisciplinaController(disciplinaDao);
        
        //IDao alunoDao =new AlunoDAOFile("ListagemAlunos.json");
        SQLiteConnector conexao2 = new SQLiteConnector("banco.sqlite");
        IDao alunoDao = new AlunoDAOBanco(conexao2.getConnection());
        this.alunoController = new AlunoController(alunoDao);
        initData();
        this.dis = d;
    }
    
    private void initData(){

        this.editando = true;

        this.habilitarCampos(false);
        this.limparCampos();

        this.atualizarTabela();
    }
    
    public void habilitarCampos(boolean flag) {
        edtCPF.setEnabled(flag);
        edtMatricula.setEnabled(flag);
        edtNome.setEnabled(flag);
        edtIdade.setEnabled(flag);
        edtAnoIngresso.setEnabled(flag);
    }

    public void limparCampos() {
        edtCPF.setText("");
        edtMatricula.setText("");
        edtNome.setText("");
        edtIdade.setText("");
        edtAnoIngresso.setText("");
    }

    public void objetoParaCampos(Aluno p) {
       edtCPF.setText(p.getCpf());
       edtMatricula.setText(p.getMatricula());
       edtNome.setText(p.getNome());
       edtIdade.setText(p.getIdade() + "");
       edtAnoIngresso.setText(p.getAnoIngresso()+ "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAluno = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        grdBook = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        lblAluno.setBackground(new java.awt.Color(102, 204, 255));
        lblAluno.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblAluno.setForeground(new java.awt.Color(255, 255, 255));
        lblAluno.setText("Select Book ");
        jPanel1.add(lblAluno);

        grdBook.setBackground(new java.awt.Color(255, 255, 255));
        grdBook.setForeground(new java.awt.Color(0, 0, 0));
        grdBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        grdBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grdBookMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(grdBook);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void grdBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grdBookMouseClicked
         Book b = this.getObjetoSelecionadoNaGrid();
       
    }//GEN-LAST:event_grdBookMouseClicked

    public Book getObjetoSelecionadoNaGrid() {
        int linhaSelecionada = grdBook.getSelectedRow();

        if (linhaSelecionada >= 0) {
            TMCadBook tmCadBook = (TMCadBook) grdBook.getModel();

             Book book = tmCadBook.getObjetoBook(linhaSelecionada);
            return book;
        }
        
        return null;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable grdBook;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAluno;
    // End of variables declaration//GEN-END:variables
}
