/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.projescolamvc.view;

import com.mycompany.projescolamvc.view.tablemodels.TMCadAluno;
import com.mycompany.projescolamvc.connection.SQLiteConnector;
import com.mycompany.projescolamvc.controller.AlunoController;
import com.mycompany.projescolamvc.controller.DisciplinaController;
import com.mycompany.projescolamvc.model.dao.AlunoDAOBanco;
import com.mycompany.projescolamvc.model.dao.AlunoDAOFile;
import com.mycompany.projescolamvc.model.dao.DisciplinaDAOBanco;
import com.mycompany.projescolamvc.model.dao.DisciplinaDAOFile;
import com.mycompany.projescolamvc.model.dao.IDao;
import com.mycompany.projescolamvc.model.entities.Aluno;
import com.mycompany.projescolamvc.model.entities.Disciplina;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author  igorxf
 */
public class JDialogSelectAluno extends javax.swing.JDialog {
    
    private boolean editando;
    private String cpfEscolhido;
    private AlunoController alunoController;
    private DisciplinaController disciplinaController;
    private Disciplina dis;
    private Aluno alunoEscolhido;
   

    
    
    public JDialogSelectAluno(java.awt.Frame parent, boolean modal,  Disciplina d) throws SQLException {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        
        //IDao disciplinaDao = new DisciplinaDAOFile("ListagemDisciplinas.json");
        
        SQLiteConnector conexao = new SQLiteConnector("banco.sqlite");
        IDao disciplinaDao = new DisciplinaDAOBanco(conexao.getConnection());
        this.disciplinaController = new DisciplinaController(disciplinaDao);
        
        
        //IDao alunoDao =new AlunoDAOFile("ListagemAlunos.json");
        
        SQLiteConnector conexao2 = new SQLiteConnector("banco.sqlite");
        IDao alunoDao = new AlunoDAOBanco(conexao2.getConnection());
        this.alunoController = new AlunoController(alunoDao);
        initData();
        this.dis = d;
    }
    
    public JDialogSelectAluno(java.awt.Dialog parent, boolean modal,  Disciplina d) throws SQLException {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        
        //IDao disciplinaDao = new DisciplinaDAOFile("ListagemDisciplinas.json");
        SQLiteConnector conexao = new SQLiteConnector("banco.sqlite");
        IDao disciplinaDao = new DisciplinaDAOBanco(conexao.getConnection());
        this.disciplinaController = new DisciplinaController(disciplinaDao);
        
        //IDao alunoDao =new AlunoDAOFile("ListagemAlunos.json");
        SQLiteConnector conexao2 = new SQLiteConnector("banco.sqlite");
        IDao alunoDao = new AlunoDAOBanco(conexao2.getConnection());
        this.alunoController = new AlunoController(alunoDao);
        initData();
        this.dis = d;
    }
    
    private void initData(){

        this.editando = true;

        this.habilitarCampos(false);
        this.limparCampos();

        this.atualizarTabela();
    }
    
    public void habilitarCampos(boolean flag) {
        edtCPF.setEnabled(flag);
        edtMatricula.setEnabled(flag);
        edtNome.setEnabled(flag);
        edtIdade.setEnabled(flag);
        edtAnoIngresso.setEnabled(flag);
    }

    public void limparCampos() {
        edtCPF.setText("");
        edtMatricula.setText("");
        edtNome.setText("");
        edtIdade.setText("");
        edtAnoIngresso.setText("");
    }

    public void objetoParaCampos(Aluno p) {
       edtCPF.setText(p.getCpf());
       edtMatricula.setText(p.getMatricula());
       edtNome.setText(p.getNome());
       edtIdade.setText(p.getIdade() + "");
       edtAnoIngresso.setText(p.getAnoIngresso()+ "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAluno = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnSelecionar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnMatricular = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblMatricula = new javax.swing.JLabel();
        edtMatricula = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        lblIdade = new javax.swing.JLabel();
        edtIdade = new javax.swing.JTextField();
        lblAnoIngresso = new javax.swing.JLabel();
        edtAnoIngresso = new javax.swing.JTextField();
        lblCPF = new javax.swing.JLabel();
        edtCPF = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        grdAluno = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        lblAluno.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblAluno.setForeground(new java.awt.Color(0, 0, 0));
        lblAluno.setText("Selecionar Aluno ");
        jPanel1.add(lblAluno);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        btnNovo.setBackground(new java.awt.Color(204, 204, 204));
        btnNovo.setForeground(new java.awt.Color(0, 0, 0));
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        jPanel2.add(btnNovo);

        btnSelecionar.setBackground(new java.awt.Color(204, 204, 204));
        btnSelecionar.setForeground(new java.awt.Color(0, 0, 0));
        btnSelecionar.setText("Selecionar");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });
        jPanel2.add(btnSelecionar);

        btnCancelar.setBackground(new java.awt.Color(204, 204, 204));
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar);

        btnMatricular.setBackground(new java.awt.Color(204, 204, 204));
        btnMatricular.setForeground(new java.awt.Color(0, 0, 0));
        btnMatricular.setText("Matricular");
        btnMatricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatricularActionPerformed(evt);
            }
        });
        jPanel2.add(btnMatricular);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        lblMatricula.setForeground(new java.awt.Color(0, 0, 0));
        lblMatricula.setText("Matricula");

        lblNome.setForeground(new java.awt.Color(0, 0, 0));
        lblNome.setText("Nome");

        lblIdade.setForeground(new java.awt.Color(0, 0, 0));
        lblIdade.setText("Idade");

        edtIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtIdadeActionPerformed(evt);
            }
        });

        lblAnoIngresso.setForeground(new java.awt.Color(0, 0, 0));
        lblAnoIngresso.setText("Ano Ingresso");

        lblCPF.setForeground(new java.awt.Color(0, 0, 0));
        lblCPF.setText("CPF");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lblCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(lblMatricula))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblIdade)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(edtMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(edtIdade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAnoIngresso, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNome, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(edtAnoIngresso, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(edtNome))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNome))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMatricula)
                        .addComponent(lblCPF)
                        .addComponent(edtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(edtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdade)
                    .addComponent(edtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAnoIngresso)
                    .addComponent(edtAnoIngresso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        grdAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(grdAluno);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       this.limparCampos();
        this.habilitarCampos(false);
        this.editando = false;
    }//GEN-LAST:event_btnCancelarActionPerformed
    
    private void btnMatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatricularActionPerformed
       Aluno a = this.alunoEscolhido;  // Obtém o aluno selecionado na interface
    
        if (a != null) {
            this.disciplinaController.atualizarDisciplinaA(dis, edtCPF.getText(), edtNome.getText(), edtIdade.getText(), edtMatricula.getText(), edtAnoIngresso.getText());
        
            JOptionPane.showMessageDialog(this, "Aluno matriculado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um aluno primeiro.");
        }
    
        this.limparCampos();
        this.habilitarCampos(false);
        this.atualizarTabela();
    }//GEN-LAST:event_btnMatricularActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
       JDialogAluno tela = null;
        try {
            tela = new JDialogAluno(this,true);
        } catch (SQLException ex) {
            Logger.getLogger(JDialogSelectAluno.class.getName()).log(Level.SEVERE, null, ex);
        }
       tela.setVisible(true);
       atualizarTabela();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
       this.alunoEscolhido = this.getObjetoSelecionadoNaGrid();
       
        String CPFEscolhido = alunoEscolhido.getCpf();
        
        Aluno alunoExistente = alunoController.buscarAluno(CPFEscolhido);

        if (alunoExistente == null) {
            JOptionPane.showMessageDialog(this, "Não existe aluno com esse cpf.");
        } else {
            this.habilitarCampos(true);
            this.objetoParaCampos(alunoExistente);
            this.editando = true;
            this.cpfEscolhido = alunoExistente.getCpf();
        }

    }//GEN-LAST:event_btnSelecionarActionPerformed

    private void edtIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtIdadeActionPerformed
    
    private void grdAlunoMouseClicked(java.awt.event.MouseEvent evt) {                                       
       Aluno a = this.getObjetoSelecionadoNaGrid();
       this.objetoParaCampos(a);
    }
    
    public Aluno getObjetoSelecionadoNaGrid() {
        int linhaSelecionada = grdAluno.getSelectedRow();

        if (linhaSelecionada >= 0) {
            TMCadAluno tmCadAluno = (TMCadAluno) grdAluno.getModel();

             Aluno aluno = tmCadAluno.getObjetoAluno(linhaSelecionada);
            return aluno;
        }
        
        return null;
    }
    
    public void atualizarTabela() {
        List<Aluno> lista = this.alunoController.listarAlunos();
        TMCadAluno tmcadaluno = new TMCadAluno(lista);
        grdAluno.setModel(tmcadaluno);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnMatricular;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JTextField edtAnoIngresso;
    private javax.swing.JTextField edtCPF;
    private javax.swing.JTextField edtIdade;
    private javax.swing.JTextField edtMatricula;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTable grdAluno;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAluno;
    private javax.swing.JLabel lblAnoIngresso;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblNome;
    // End of variables declaration//GEN-END:variables
}
